# Generated by Django 5.2.1 on 2025-05-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Toyota', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='Седан', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('user', 'Пайдаланушы'), ('guest', 'Қонақ')], max_length=20),
        ),
    ]
