# Generated by Django 5.2.1 on 2025-05-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_make_remove_car_status_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Қолжетімді'), ('unavailable', 'Қол жетімсіз')], default='available', max_length=20),
        ),
    ]
