# Generated by Django 5.2.1 on 2025-05-21 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='cars/'),
        ),
        migrations.CreateModel(
            name='ProfitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_rented', models.PositiveIntegerField()),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car')),
            ],
        ),
    ]
