# Generated by Django 5.2.1 on 2025-05-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_status_alter_car_image_profitrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profitrecord',
            old_name='days_rented',
            new_name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Белсенді'), ('completed', 'Аяқталған'), ('cancelled', 'Бас тартылды')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='profitrecord',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profitrecord',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
