# Generated by Django 5.2.1 on 2025-05-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_days_rented_profitrecord_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Әкімші'), ('user', 'Пайдаланушы'), ('guest', 'Қонақ')], max_length=20),
        ),
    ]
