# Generated by Django 5.2.1 on 2025-05-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Қолжетімді'), ('unavailable', 'Қол жетімсіз')], default='available', max_length=20),
        ),
    ]
