# Generated by Django 5.2.1 on 2025-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон нөмірі'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('user', 'Пайдаланушы'), ('guest', 'Қонақ')], max_length=20),
        ),
    ]
