# Generated by Django 5.2.1 on 2025-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_employee_phone_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
