# Generated by Django 5.2.1 on 2025-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_booking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, verbose_name='Координаттар (лат,лон)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автокөліктің мекенжайы'),
        ),
    ]
